# Generated by Django 6.0.6 on 2026-08-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.FloatField(help_text='Internal width in cm')),
                ('height', models.FloatField(help_text='Internal height in cm')),
                ('depth', models.FloatField(help_text='Internal depth in cm')),
                ('max_weight', models.FloatField(help_text='Maximum weight capacity in kg')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('width', models.FloatField(help_text='Width in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('depth', models.FloatField(help_text='Depth in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='box_selection.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_selection.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_utilization', models.FloatField(blank=True, help_text='Volume utilization percentage', null=True)),
                ('weight_utilization', models.FloatField(blank=True, help_text='Weight utilization percentage', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the selected box', max_digits=10, null=True)),
                ('packing_layout', models.JSONField(blank=True, default=list, help_text='List of placed items with coordinates and orientation')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='box_selection.order')),
                ('selected_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='box_selection.box')),
            ],
        ),
    ]
