# Generated by Django 5.2.17 on 2026-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_selection', '0002_shipmentrecommendation_error_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='depth',
            field=models.DecimalField(decimal_places=2, help_text='Internal depth in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Internal height in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='box',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, help_text='Maximum weight capacity in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Internal width in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=2, help_text='Depth in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='Weight in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=8),
        ),
    ]
